apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# Size LARGE — resources do container. Pareia com size=large da AppNamespace
# Claim (quota cpu8/8Gi).
patches:
  - target:
      kind: Deployment
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: "2"
            memory: 1Gi
